# Volumes used in this app
volumes:
        wordpress:

# Services used in this app
services:
        # nginx service
        nginx:
                container_name: nginx
                build: ./requirements/nginx/
                ports:
                        - "80:80"
                volumes:
                        - wordpress:/var/www/wordpress

        # wordpress + php-fpm service
        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress/
                volumes:
                        - wordpress:/var/www/wordpress
