CREATE DATABASE IF NOT EXISTS `wordpress`;
CREATE USER IF NOT EXISTS 'aymane'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'aymane'@'%' IDENTIFIED BY '1234';
FLUSH PRIVILEGES;
